name: "The Fever"
title: "Bandeoke experience for hire"
description:
  - "The Fever are a live band karaoke experience for hire based in" 
  - ". The perfect addition to parties, weddings, and festivals."
baseurl: ""
url: "https://thefever.band"
email: "info@thefever.band"

meta_image: "cover.jpg"
hero_video_id: "eagdJADNbDc"
staticforms_key: "e20faf4c-267c-47fe-b62f-f9a52dfbd7c8"
google_tag_id: "G-M2561NPM9B"
recaptcha_sitekey: "6LeqsaMoAAAAAEeh6T7GRGh-M7663g3mM6wLpzpj"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "The Fever"
      location: "Hampshire"

plugins:
  - jekyll-sitemap

sass:
  style: compressed